### ISSUE TITLE
Fidget doesn't spin in Chrome mobile

### ISSUE THREAD

**Issue by donroyco** [samccone/fidgetspin.xyz#10]
I don't think the width issue, as mentioned in #6, will have an influence on this. It worked before (?).

**Comment by samccone** [comment]
@donroyco I think this should be fixed... can you confirm?

**Comment by donroyco** [comment]
@samccone It's still broken. The width is not 100%, but more.

**Comment by samccone** [comment]
hey @donroyco, I just got my hands on an iphone and put the fix into place, mind confirming?

**Comment by donroyco** [comment]
@samccone Yes, it's working again. Thanks for your help. _Working fidget confirmed_.
